name: group_m4ker
description: Group Maker

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^0.4.0

  googleapis: any
  googleapis_auth: any
  url_launcher: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - secrets.json

